### ISSUE TITLE
html的lang="en-us"属性是否有必要加上？

### ISSUE THREAD

**Issue by kamifun** [AlloyTeam/alloyteam.github.com#6]
刚刚去看了你们的规范，然后再看看你们的index.html，发现没有lang="xxx"，请问加还是不加好？

**Comment by moscartong** [comment]
lang屬性可以用來：
> Identifying the language of your content allows you to automatically do a number of things, from changing the look and behavior of a page, to extracting information, to changing the way that an application works

W3C說，這個屬性現在基本沒什麼亂用，但是開發的時候加上，以後有相關特性的時候就可以馬上得到支持，總比以後需要的時候再去改代碼好：https://www.w3.org/International/questions/qa-lang-why.en
